version: '3'
services:
  jeager:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - custom
networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
